### ISSUE TITLE
Is a relative path prefix needed for Command?

### ISSUE THREAD

**Issue by calebwherry** [robertdfrench/git-pr#8]
Does just using the exe name work instead of having to join with the full path?

_Originally posted by @calebwherry in https://github.com/robertdfrench/git-pr/pull/1#r725656028_

**Comment by robertdfrench** [comment]
In e187ac1544f4b89a0830c3ba20b18f084d7b009c you showed that we can just write `Path::new("./target/debug/whatever")` and it will still work on Windows. But to answer this question completely, I removed the leading `./` and all the tests still passed:

```diff
     #[test]
     fn query_version_info() {
-        let path = Path::new("./target/debug/fake_git");
+        let path = Path::new("target/debug/fake_git");
         let fake_git = Git::with_path(path);
         let version = fake_git.version().unwrap();
         assert!(version.starts_with("fake_git version 1"));
``` 

So you are right; we do **not** need the relative prefix here. I am inclined to say we leave it anyhow, since it's a little more explicit and Windows seems to tolerate it. But if you want to drop it, I'm not opposed.

**Comment by calebwherry** [comment]
I'm fine with leaving it, I think it makes it more clear on the intention of running from the PWD.
